### ISSUE TITLE
Deployment documentation 

### ISSUE THREAD

**Issue by acds** [normj/LambdaNETCoreSamples#1]
Hi

This is very useful, however it would be great if you could add a section to the readme on how you deploy such a setup to AWS.

Does one use the dotnet lambda tools cli or the serverless npm module ? the AWS docs are not clear at all...that I can find.

There seem to be documentation for published via the Visual Studio adding, but that does not help if one is not using Visual Studio....

Thanks!

**Comment by normj** [comment]
Good suggestion. I was assuming the viewer was already familiar with the AWS .NET Lambda tooling but I can add a section about deployment.

**Comment by acds** [comment]
Hi @normj thanks for fixing the lambda tools per (https://github.com/aws/aws-extensions-for-dotnet-cli/issues/76)

Familiarity is relative....there seems to be a lot of moving parts here. 

As an aside I assume one can support both regular controllers in this approach and `FunctionHandlers` - such that one can support say the Lambda Authorizer in the same code base.

I got as far as attempting to manually create a CloudFormation Stack given the [template](https://github.com/normj/LambdaNETCoreSamples/blob/master/CustomRuntimeAspNetCore/serverless.template) but get an error:
```
Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [AspNetCoreFunction] is invalid. Either 'InlineCode' or 'CodeUri' must be set
``` 

I assume this manual setup is needed as a call to `DotNetCliTools lambda deploy-serverles` promos for the CloudFormation Stack name

**Comment by acds** [comment]
@norm Thanks, as above I think I got the `dotnet lambda deploy-serverless` to work with .Net Core 2.2. However I have it set not to `selfcontained=true`?

It would be good to also have examples for how onc can handle `APIGatewayCustomAuthorizerRequest` in the scope of a `Amazon.Lambda.AspNetCoreServer` similar to the `APIGatewayProxyRequest` [here](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.APIGatewayEvents#microsoftaspnetcoremvc-controller)

**Comment by normj** [comment]
Working on repurposing this repo for .NET 6. So far replaced the samples with one .NET 6 and was more explicit in the documentation about deployment.
