### ISSUE TITLE
.net Core preview 7 nuget package

### ISSUE THREAD

**Issue by dtminnaar** [normj/LambdaNETCoreSamples#3]
Good day, 

Firstly, thank you very much for this example project!

I have tried to create a new Amazon.Lambda.AspNetCoreServer .dll using .net core preview 7 and have not had any luck compiling it.

Can you please let me know what I need to do to get that library compiling? Or please provide a nuget package that targets preview 7?

I keep running into the following errors:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Internal' does not exist in the namespace 'Microsoft.AspNetCore.Hosting' (are you missing an assembly reference?)	Amazon.Lambda.AspNetCoreServer (netcoreapp3.0)	C:\Dev\Amazon.Lambda.AspNetCoreServer\Internal\LambdaServer.cs	10	Active
Error	CS0246	The type or namespace name 'HostingApplication' could not be found (are you missing a using directive or an assembly reference?)	Amazon.Lambda.AspNetCoreServer (netcoreapp3.0)	C:\Dev\Amazon.Lambda.AspNetCoreServer\Internal\LambdaServer.cs	23	Active
... snip the rest
`

**Comment by normj** [comment]
I'm working on getting this package to work in preview 7. You can track the progress with the following GitHub issue. https://github.com/aws/aws-lambda-dotnet/issues/481
