### ISSUE TITLE
Use Lambda .NET 2.2 with SQS Event

### ISSUE THREAD

**Issue by pawelkasperek** [normj/LambdaNETCoreSamples#4]
Hi,

This sample use ApiGateway events (request) to call .NET Core ASP.NET 2.2 application. I looked on net many samples that use AWS Lamdba with .NET Core 2.2, and all use only API Gateway events. Is possible use others events ex. SQSEvent with AWS Lambda and .NET 2.2 runtime  ?

**Comment by normj** [comment]
Yes, the blueprint that is in Visual Studio for **Custom Runtimes** is configured for .NET Core 2.2. Currently the parameter is taking a string but you can easily add one of [the event NuGet packages](AWS_PROFILE) and change the string parameter to event type you want to use.
