### ISSUE TITLE
Using LoadBalancer with Custom Runtime

### ISSUE THREAD

**Issue by richardkeller411** [normj/LambdaNETCoreSamples#6]
If we change the Lambda Entry point to Amazon.Lambda.AspNetCoreServer.ApplicationLoadBalancerFunction   the functionHandler in the Main will need to change as well.

**Comment by normj** [comment]
Correct, you will need to change the references to APIGatewayProxyRequest and APIGatewayProxyResponse to the application load balancer versions which are ApplicationLoadBalancerRequest and ApplicationLoadBalancerResponse.
